name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle build
        run: ./gradlew build

  release:
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
     steps:
      - name: Get release information
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "RELEASE_NUMBER=${LATEST_TAG:1}" >> $GITHUB_ENV
      #- name: Publish to Maven Repository
      #  run: ./gradlew publishToMavenCentral
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ env.LATEST_TAG }}
          generate_release_notes: true
          files: |
            build/libs/TeleightBots-${{ env.RELEASE_NUMBER }}-*.jar
